Faq section
front-end-by-rimantas/42-grupe-portfolio-react pull request #112
Opened 2023-02-07 12:43 UTC by xzcjdvd

2023-02-07 14:12 UTC, Arshunas approved these changes

2023-02-07 15:00 UTC, vitgri1 requested changes

2023-02-07 15:00 UTC, vitgri1 commented on index.html
> +            <div class="text-link col-6 ml-3">
Labai susispaudzia prie siauro ekrano, gal is viso nereikia col, jei centruoja visada

2023-02-09 20:17 UTC, vitgri1 approved these changes
LGTM

2023-02-10 07:14 UTC, inga911 approved these changes

2023-02-10 07:15 UTC, merged