S app section
front-end-by-rimantas/42-grupe-portfolio-react pull request #114
Opened 2023-02-07 14:13 UTC by Arshunas

2023-02-07 15:04 UTC, vitgri1 requested changes

2023-02-07 15:04 UTC, vitgri1 commented on index.html
> +                <div class="main-para">sApp is available for all devices, consectetur adipisicing elit. Itaque at harum quam explicabo. Aliquam optio, delectus, dolorem quod neque eos totam. Delectus
Maziau teksto prie siauro ekrano *visible/hidden*

2023-02-07 19:19 UTC, vitgri1 requested changes

2023-02-07 19:19 UTC, vitgri1 commented on css/pages/home.css
> +@media (min-width: 136px) {
kam to reikia?

2023-02-08 13:31 UTC, vitgri1 approved these changes
Good enough

2023-02-08 17:20 UTC, xzcjdvd requested changes
Minimalaus pakeitimo reik

2023-02-08 17:20 UTC, xzcjdvd commented on css/pages/home.css
> +.sApp{
atstumk nuotraukas nuo virsaus siektiek, kaip orginale

2023-02-08 17:31 UTC, Arshunas commented on css/pages/home.css
> +.sApp{
done

2023-02-09 10:01 UTC, xzcjdvd approved these changes
lgtm

2023-02-09 10:08 UTC, vitgri1 approved these changes

2023-02-09 11:12 UTC, merged