How section hover
front-end-by-rimantas/42-grupe-portfolio-react pull request #120
Opened 2023-02-08 17:20 UTC by xzcjdvd

2023-02-09 07:36 UTC, Arshunas approved these changes

2023-02-09 10:11 UTC, vitgri1 requested changes

2023-02-09 10:11 UTC, vitgri1 commented on css/pages/home.css
> +@media (min-width: 992px) {
prasideda nuo _medium_, ne nuo _large_
![image](https://user-images.githubusercontent.com/121028126/217783178-004b59c5-5f81-408d-8867-3d38f71ac040.png)

2023-02-13 06:53 UTC, mstepno approved these changes

2023-02-13 06:56 UTC, vitgri1 approved these changes

2023-02-13 06:58 UTC, merged