BASE CSS #28
front-end-by-rimantas/42-grupe-portfolio-react pull request #43
Opened 2023-02-01 13:37 UTC by Arshunas

Signed-off-by: Sarunas <sarunas.stankevicius@mailbox.org>

2023-02-01 14:12 UTC, vitgri1 requested changes

2023-02-01 14:12 UTC, vitgri1 commented on css/base/base.css
>  /* base css end */
kodas turetu buti tarp komentaru

2023-02-01 14:12 UTC, vitgri1 commented on css/base/base.css
> +    text-decoration: none;
mes norim at visu linku, ne tik p>a

2023-02-01 15:19 UTC, vitgri1 requested changes

2023-02-01 15:19 UTC, vitgri1 commented on css/base/base.css
> +}
No

2023-02-01 15:19 UTC, vitgri1 commented on css/base/base.css
> +
Random extra lines

2023-02-01 15:30 UTC, vitgri1 requested changes

2023-02-01 15:30 UTC, vitgri1 commented on css/base/base.css
> +    color: #222222;
Random color

2023-02-01 15:30 UTC, vitgri1 commented on css/base/base.css
> +p > a {
per didelis prioritetas/ tik atvejai kai 
```
<p>text <a>link<a/> </p>
```

2023-02-01 15:30 UTC, vitgri1 commented on css/base/base.css
> +    color: #222222;
random color

2023-02-01 15:30 UTC, vitgri1 commented on css/base/base.css
> +    text-decoration: none;
jau aprasyta

2023-02-01 15:30 UTC, vitgri1 commented on css/base/base.css
> +a:hover {
truksta spalvos keitimo

2023-02-01 20:44 UTC, vitgri1 approved these changes
LGTM

2023-02-02 06:55 UTC, inga911 approved these changes

2023-02-02 06:56 UTC, merged