Express dezuciu hover  #11
front-end-by-rimantas/42-grupe-portfolio-react pull request #84
Opened 2023-02-05 12:58 UTC by vitgri1

2023-02-05 19:14 UTC, Arshunas submitted a review, later dismissed

2023-02-05 22:24 UTC, xzcjdvd requested changes
Viskas super apart seseli

2023-02-05 22:24 UTC, xzcjdvd commented on css/pages/home.css
>      box-shadow: 0 0.25em 0.5em rgba(0,0,0,.075);
Noretusi man asmeniskai gal bent didesniu seseliu pagal dizaina?

2023-02-06 15:53 UTC, inga911 approved these changes
LGTM! 👍

2023-02-06 16:37 UTC, xzcjdvd approved these changes
Super!

2023-02-06 19:34 UTC, merged