Hero section
front-end-by-rimantas/42-grupe-portfolio-react pull request #88
Opened 2023-02-05 13:33 UTC by vitgri1

2023-02-05 19:14 UTC, Arshunas approved these changes

2023-02-05 21:44 UTC, xzcjdvd requested changes
O tai gal padaryt hero sectiona 100vh? nes lenda tas premium features dabar

2023-02-06 16:38 UTC, xzcjdvd approved these changes
LGTM

2023-02-07 11:43 UTC, Arshunas approved these changes

2023-02-07 11:50 UTC, merged