sub section
front-end-by-rimantas/42-grupe-portfolio-react pull request #90
Opened 2023-02-05 22:20 UTC by xzcjdvd

2023-02-06 06:48 UTC, Arshunas approved these changes

2023-02-06 16:08 UTC, inga911 approved these changes
👍

2023-02-06 20:05 UTC, vitgri1 requested changes

2023-02-06 20:05 UTC, vitgri1 commented on index.html
> +    <div class="container col-12 col-lg-6">
Konteineris nenaudoja *col-* klases

2023-02-06 21:56 UTC, xzcjdvd commented on index.html
> +    <div class="container col-12 col-lg-6">
fixec

2023-02-07 11:41 UTC, vitgri1 approved these changes
LGTM

2023-02-07 11:43 UTC, Arshunas approved these changes

2023-02-07 11:44 UTC, merged