Device section
front-end-by-rimantas/42-grupe-portfolio-react pull request #91
Opened 2023-02-06 12:33 UTC by xzcjdvd

2023-02-06 12:40 UTC, Arshunas approved these changes

2023-02-06 19:52 UTC, vitgri1 requested changes
Section title ir iconai dezutese net ne panasus

2023-02-06 19:52 UTC, vitgri1 commented on index.html
> +                        <h2 class="section-tittle">
*section-title* atsinesa su savimi *::after* elementa, reiketu ji nutrinti, jei naudoji sioje vietoje

2023-02-07 11:08 UTC, xzcjdvd commented on index.html
> +                        <h2 class="section-tittle">
done

2023-02-07 11:27 UTC, vitgri1 approved these changes
LGTM

2023-02-07 11:28 UTC, inga911 approved these changes

2023-02-07 11:36 UTC, merged